### ISSUE TITLE
node v10.16.0 in trunk not usable

### ISSUE THREAD

**Issue by jfqd** [TritonDataCenter/pkgsrc#203] opened 2019-06-03 10:32 UTC
Latest node version 10.16.0 in trunk, build date: '01-Jun-2019 01:28', is failing to start:

```
$ node --version
ld.so.1: node: fatal: relocation error: R_AMD64_32: file /opt/local/bin/node: symbol getentropy: value 0xfffffc7fef12ac60 does not fit
```

**Comment by jperkin** [comment] 2019-06-19 11:55
I couldn't reproduce this, was it reproducible for you?  It has been rebuilt with a newer GCC though so I don't have the exact bits that you may have used.

**Comment by jfqd** [comment] 2019-07-01 12:46
I am using trunk and just installed latest node, same issue:

```
$ node --version
ld.so.1: node: fatal: relocation error: R_AMD64_32: file /opt/local/bin/node: symbol getentropy: value 0xfffffc7fef12ac60 does not fit
Killed
```

**Comment by jperkin** [comment] 2019-07-01 12:49
What platform version are you running on?

**Comment by jfqd** [comment] 2019-07-01 12:51
20190509T005736Z

**Comment by jfqd** [comment] 2020-03-09 16:51
@jperkin  It seems this have been fixed, right?

**Comment by jperkin** [comment] 2020-03-10 10:43
Yeh sorry, forgot to close this out.

**Closed as completed by jperkin** 2020-03-10 10:43 UTC
