### ISSUE TITLE
[darwin] Missing package: mutt

### ISSUE THREAD

**Issue by baskerville** [TritonDataCenter/pkgsrc#13] opened 2017-08-09 11:02 UTC

**Comment by bahamat** [comment] 2017-08-13 20:07
This package *has* been available in the past, because I currently have it installed.

**Comment by jperkin** [comment] 2017-08-16 10:53
The build was masked by the gpgme failure caused by its most recent update, and should be fixed in  aa32b0f541be70579569bd0e2bc61f17350a9ac5.  Latest macOS build will start today so hopefully should be available again by the end of the week.  I'll add mutt to the list of required packages (I use it too) so that publishing will be disabled if it isn't available.

**Comment by jperkin** [comment] 2017-08-24 06:21
This is now available again.

**Closed as completed by jperkin** 2017-08-24 06:21 UTC
